name: Docker Image CI

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
  pull_request:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mao-server-discovery:$(date +%s)
