name: Go

on:
  push:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
  pull_request:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
  
jobs:
  go-versions:
    name: Lookup Go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: arnested/go-version-action@v1
        id: versions
  build:
    runs-on: ubuntu-latest
    needs: go-versions
    strategy:
      matrix:
        version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}
        check-latest: true

    - name: Build
      run: go build -v -a ./...

    - name: Test
      run: go test -v ./...
