# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go All

on:
  push:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
  pull_request:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
    
jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "ubuntu-22.04", "ubuntu-20.04", "macos-latest"]
        go-version: ["1.21", "1.20", "1.19", "1.18"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...
      shell: bash

    - name: Show Build Result
      run: ls -al
      shell: bash

    - name: Test
      run: go test -v ./...
      shell: bash
