# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go (Linux/Win/MacOS)

on:
  push:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
  pull_request:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "ubuntu-22.04", "ubuntu-24.04", "macos-latest"]
        go-version: ["1.25", "1.24", "1.23", "1.22", "1.21", "1.20", "1.19", "1.18"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v -a -ldflags "-X main.GIT_VERSION=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse HEAD)"

    - name: Show Build Result
      run: ls -al
      shell: bash

    - name: Test
      run: go test -v ./...
      shell: bash
      
    - name: Run Check Version
      run: ./MaoServerDiscovery -v
